### ISSUE TITLE
crates.io namespace claims

### ISSUE THREAD

**Issue by stevenroose** [klebs6/bitcoin-rs#2]
This project seems very much a work in progress and you are claiming dozens of crate names prefixed with bitcoin- in the crates.io repository..

Are you open to conversation in potentially giving up some of the crate names for the rust-bitcoin organization?

**Comment by klebs6** [comment]
yes, you can have the ones you need.

perhaps there is a way to distribute crate ownership across a wide number of parties.

by doing so, it seems to me that the total strength and resilience of the network compounds.

in any case, the task of translating the full bitcoin core from cpp to rust is now fully parallelized.

**Comment by stevenroose** [comment]
Thanks for your flexibility. I guess the conversation moved into that rust-bitcoin thread (https://github.com/rust-bitcoin/rust-bitcoin/pull/1818) so we can close this issue?
