### ISSUE TITLE
Request: improve the top-level readme with more info

### ISSUE THREAD

**Issue by RecRanger** [klebs6/bitcoin-rs#3]
What project is this being translated from? You mention a git commit hash, but don't mention what repository that hash is from.

What transpiler was used to convert this from C++?

**Comment by klebs6** [comment]
greetings -- this translation comes from the c++ upstream `https://github.com/bitcoin/bitcoin`

the transpiler is found here: `https://github.com/klebs6/chomper`

these are good additions to the readme. thank you for suggesting them.  i will add them to the readme and provide an update.

**Comment by klebs6** [comment]
readme updated! do let me know if you have any questions!
best,
-thomas
